In [24]:
import numpy as np
from numpy import linalg

**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [20]:
N=10
np.arange(N-1, -1,-1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [21]:
np.diag(np.arange(N-1, -1,-1), k=0).sum()

45

**Задание 3**
Решите систему уравнений:
- 4x + 2y + z = 4
- x + 3y = 12
- 5y + 4z = -3

In [38]:
linalg.solve(np.array( [ [4, 2, 1], [1, 3, 1], [1, 1, 4] ]), np.array( [ 4, 12, -3 ]))

array([-1.02777778,  4.91666667, -1.72222222])

In [39]:
# развернуто
l = np.array( [ [4, 2, 1], [1, 3, 1], [1, 1, 4] ])
r = np.array( [ 4, 12, -3 ])
res=linalg.solve(l, r)
# 4*res[0]+2*res[1]+res[2]
np.dot(l, linalg.solve(l, r))

array([ 4., 12., -3.])